name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore VaultStream.Api/VaultStream.Api.csproj
    - name: Build
      run: dotnet build VaultStream.Api/VaultStream.Api.csproj --no-restore
    - name: Test Domain
      run: dotnet test VaultStream.Domain.Tests/VaultStream.Domain.Tests.csproj
    - name: Test Application
      run: dotnet test VaultStream.Application.Tests/VaultStream.Application.Tests.csproj
    - name: Docker Build
      run: docker build -t vaultstream-api:latest .
